# То же самое, что и в серверном Dockerfile.

FROM mvn:latest

# Импортируем 'client.py' в папку '/client/'.

ADD mvnw.cmd /backend/

# Устанавливаем в качестве рабочей директории '/client/'.

WORKDIR /backend/
